<?php

namespace CheckoutStepper\Widgets;

use Ceres\Widgets\Helper\BaseWidget;

class StepperWidget extends BaseWidget {
    protected $template = "CheckoutStepper::Widgets.StepperWidget";

    protected function getTemplateData($widgetSettings, $isPreview)
    {
        return parent::getTemplateData($widgetSettings, $isPreview); // TODO: Change the autogenerated stub
    }
}

?>